apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffic-control
  namespace: iot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffic-control
  template:
    metadata:
      labels:
        app: traffic-control
    spec:
      containers:
        - name: traffic-control
          image: traffic-control:dev
          imagePullPolicy: Never
          ports:
            - containerPort: 8082
          env:
            - name: CONTROLLER_PROMETHEUS_URL
              value: http://prometheus:9090
            - name: CONTROLLER_MQTT_BROKER
              value: tcp://host.minikube.internal:1883
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://host.minikube.internal:5433/iot
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: traffic-control
  namespace: iot
spec:
  type: NodePort
  selector:
    app: traffic-control
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30082
