services:
  emqx-dt:
    image: emqx/emqx-enterprise:latest
    ports:
      - "1883:1883"
      - "18083:18083"
    volumes:
      - ./emqx-dt.conf:/opt/emqx/etc/emqx.conf
    depends_on:
      kafka-init:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "emqx", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

#  emqx-raw:
#    image: emqx/emqx-enterprise:latest
#    ports:
#      - "1884:1883"
#      - "18084:18083"   # EMQX dashboard (raw broker)
#    volumes:
#      - ./emqx-raw.conf:/opt/emqx/etc/emqx.conf
#    healthcheck:
#      test: ["CMD", "emqx", "ping"]
#      interval: 10s
#      timeout: 5s
#      retries: 10


  influxdb:
    image: influxdb:2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminadmin
      - DOCKER_INFLUXDB_INIT_ORG=iot
      - DOCKER_INFLUXDB_INIT_BUCKET=sensor_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-secret-token

  kafka:
    image: apache/kafka:3.9.0
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:29092,CONTROLLER://:29093,EXTERNAL://:9092,K8S://:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,EXTERNAL://localhost:9092,K8S://host.minikube.internal:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,K8S:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9092" ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka-init:
    image: apache/kafka:3.9.0
    depends_on:
      kafka:
        condition: service_healthy
    restart: "no"
    entrypoint: ["/bin/bash", "-c"]
    command:
      - |
        set -e
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 \
          --create --if-not-exists \
          --topic telemetry.observations \
          --partitions 8 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 \
          --alter --topic telemetry.observations --partitions 8 || true
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 \
          --create --if-not-exists \
          --topic commands.devices \
          --partitions 1 --replication-factor 1
        /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:29092 --describe

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    ports:
      - "9308:9308"
    command:
      - --kafka.server=kafka:29092
    depends_on:
      kafka:
          condition: service_healthy

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    ports:
      - "9187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@timescaledb:5433/iot?sslmode=disable"
    depends_on:
      timescaledb:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - kafka-exporter
      - postgres-exporter

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local-kraft-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
    depends_on:
      - kafka

  timescaledb:
    image: timescale/timescaledb:latest-pg17
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iot
      PGPORT: 5433
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d iot -p 5433" ]
      interval: 5s
      timeout: 5s
      retries: 5

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  sink-service:
    build:
      context: ../sink-service
    restart: unless-stopped
    env_file:
      - ../sink-service/.env
    depends_on:
      kafka:
        condition: service_healthy
      timescaledb:
        condition: service_healthy
